dm_rooms
nexy7574/nio-bot pull request #15
Opened 2024-02-29 04:26 UTC by fvjosef21

This is a bug fix for the send_message, get_dm_rooms, and create_dm_room functions.

I also added code to do a lazy check if there are rooms that are on the server, but not on the bot. I am not sure
why this is happening.

I added a call to set the m.direct type on the newly created dm_room. This is not really supported by
the nio-sdk library, which is missing the MDirectResponse type.

2024-02-29 17:41 UTC, nexy7574 requested changes
Looks good, just a couple (mainly formatting) things that need doing before this can be merged :)

2024-02-29 17:41 UTC, nexy7574 commented on src/niobot/client.py
> +                    raise RuntimeError("DM room %r was created, but could not be found in the room list!" % room_id)
Could you add documentation for the RuntimeError exception into the docstring? only ValueError and MessageException are documented at the moment

2024-02-29 17:41 UTC, nexy7574 commented on src/niobot/client.py
> +            nio.Api._build_path(    ["user", self.user_id, "account_data", "m.direct"],
The whitespace is a little odd here - could you run `ruff check --fix` and `ruff format` & push on your fork? just for styling consistency

2024-02-29 17:41 UTC, nexy7574 commented on src/niobot/client.py
> +        dm_rooms[user_id] = [result.room_id]
Just being pedantic here but wouldn't it be cleaner to just do `dm_rooms = {user_id: [result.room_id]}`?

2024-03-07 23:23 UTC, fvjosef21 commented
Fixed the comments. Not sure how to submit PR again.

2024-03-14 01:40 UTC, nexy7574 commented
No need to re-submit, changes are automatically added to the PR :)

2024-03-14 01:48 UTC, nexy7574 approved these changes
Looks good!

2024-03-14 01:48 UTC, nexy7574 commented
All checks passed, merging.

2024-03-14 01:48 UTC, merged